name: create-whatever
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
      - run: yarn install
      - run: yarn release:trigger
